name: ml
channels:
  - anaconda
  - conda-forge
dependencies:
  - absl-py=1.0.0
  - aiohttp=3.8.1
  - aiosignal=1.2.0
  - anyio=3.5.0
  - appnope=0.1.3
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - astroid=2.11.5
  - asttokens=2.0.5
  - async-timeout=4.0.2
  - attrs=21.4.0
  - autopep8=1.6.0
  - babel=2.10.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - beautifulsoup4=4.11.1
  - black=22.3.0
  - bleach=5.0.0
  - blinker=1.4
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2021.10.8
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=5.0.0
  - cairo=1.16.0
  - certifi=2021.10.8
  - cffi=1.15.0
  - charset-normalizer=2.0.12
  - click=8.1.3
  - colorama=0.4.4
  - cryptography=36.0.2
  - cycler=0.11.0
  - dataclasses=0.8
  - debugpy=1.6.0
  - decorator=5.1.1
  - defusedxml=0.7.1
  - dill=0.3.4
  - entrypoints=0.4
  - et_xmlfile=1.0.1
  - executing=0.8.3
  - expat=2.4.8
  - ffmpeg=4.3.2
  - flit-core=3.7.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.33.3
  - freetype=2.10.4
  - frozenlist=1.3.0
  - gettext=0.19.8.1
  - giflib=5.2.1
  - gmp=6.2.1
  - gnutls=3.6.13
  - google-auth=2.6.6
  - google-auth-oauthlib=0.4.6
  - graphite2=1.3.13
  - grpcio=1.46.1
  - h5py=3.6.0
  - harfbuzz=3.4.0
  - hdf5=1.12.1
  - icu=69.1
  - idna=3.3
  - importlib-metadata=4.11.3
  - importlib_metadata=4.11.3
  - importlib_resources=5.7.1
  - ipykernel=6.13.0
  - ipython=8.3.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.7.0
  - isort=5.10.1
  - jasper=2.0.33
  - jbig=2.1
  - jedi=0.18.1
  - jinja2=3.1.2
  - joblib=1.1.0
  - jpeg=9e
  - json5=0.9.5
  - jsonschema=4.5.1
  - jupyter=1.0.0
  - jupyter_client=7.3.1
  - jupyter_console=6.4.3
  - jupyter_core=4.10.0
  - jupyter_server=1.16.0
  - jupyterlab=3.3.4
  - jupyterlab_pygments=0.2.2
  - jupyterlab_server=2.13.0
  - jupyterlab_widgets=1.1.0
  - kiwisolver=1.4.2
  - krb5=1.19.3
  - lame=3.100
  - lazy-object-proxy=1.7.1
  - lcms2=2.12
  - lerc=3.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcurl=7.83.1
  - libcxx=14.0.3
  - libdeflate=1.10
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libglib=2.70.2
  - libiconv=1.16
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libnghttp2=1.47.0
  - libopenblas=0.3.20
  - libopencv=4.5.5
  - libpng=1.6.37
  - libprotobuf=3.19.4
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libtiff=4.3.0
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.13
  - libzlib=1.2.11
  - llvm-openmp=14.0.3
  - lz4-c=1.9.3
  - markdown=3.3.7
  - markupsafe=2.1.1
  - matplotlib=3.5.2
  - matplotlib-base=3.5.2
  - matplotlib-inline=0.1.3
  - mccabe=0.7.0
  - mistune=0.8.4
  - multidict=6.0.2
  - munkres=1.1.4
  - mypy_extensions=0.4.3
  - natsort=8.1.0
  - nbclassic=0.3.7
  - nbclient=0.5.13
  - nbconvert=6.4.5
  - nbformat=5.4.0
  - ncurses=6.3
  - nest-asyncio=1.5.5
  - nettle=3.6
  - ninja=1.10.2
  - notebook=6.4.11
  - notebook-shim=0.1.0
  - numpy=1.21.6
  - oauthlib=3.2.0
  - opencv=4.5.5
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openpyxl=3.0.9
  - openssl=1.1.1o
  - packaging=21.3
  - pandas=1.4.2
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pathspec=0.9.0
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.1.0
  - pip=22.1
  - pixman=0.40.0
  - platformdirs=2.5.1
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.29
  - prompt_toolkit=3.0.29
  - psutil=5.9.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - py-opencv=4.5.5
  - pyasn1=0.4.8
  - pycodestyle=2.8.0
  - pycparser=2.21
  - pygments=2.12.0
  - pyjwt=2.4.0
  - pylint=2.13.1
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pyrsistent=0.18.1
  - pysocks=1.7.1
  - python=3.9.12
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.15.3
  - python_abi=3.9
  - pytz=2022.1
  - pyu2f=0.1.5
  - pyzmq=22.3.0
  - readline=8.1
  - requests=2.27.1
  - requests-oauthlib=1.3.1
  - rsa=4.8
  - scikit-learn=1.0.2
  - scipy=1.8.0
  - send2trash=1.8.0
  - setuptools=62.2.0
  - sleef=3.5.1
  - sniffio=1.2.0
  - soupsieve=2.3.1
  - sqlite=3.38.5
  - stack_data=0.2.0
  - terminado=0.13.3
  - testpath=0.6.0
  - threadpoolctl=3.1.0
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - tornado=6.1
  - tqdm=4.63.0
  - traitlets=5.2.0
  - typed-ast=1.5.3
  - typing-extensions=4.2.0
  - typing_extensions=4.2.0
  - tzdata=2022a
  - unicodedata2=14.0.0
  - urllib3=1.26.9
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.3.2
  - werkzeug=2.1.2
  - wheel=0.37.1
  - widgetsnbextension=3.6.0
  - wrapt=1.14.1
  - x264=1!161.3030
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.5
  - yarl=1.7.2
  - zeromq=4.3.4
  - zipp=3.8.0
  - zlib=1.2.11
  - zstd=1.5.2
  - pip:
    - astunparse==1.6.3
    - docker-pycreds==0.4.0
    - flatbuffers==2.0
    - gast==0.5.3
    - gitdb==4.0.9
    - gitpython==3.1.27
    - google-pasta==0.2.0
    - keras==2.8.0
    - keras-preprocessing==1.1.2
    - libclang==14.0.1
    - opt-einsum==3.3.0
    - pathtools==0.1.2
    - promise==2.3
    - protobuf==3.20.1
    - pyasn1-modules==0.2.8
    - pyyaml==6.0
    - sentry-sdk==1.5.12
    - setproctitle==1.2.3
    - shortuuid==1.0.9
    - six==1.15.0
    - smmap==5.0.0
    - termcolor==1.1.0
    - tf-estimator-nightly==2.8.0.dev2021122109
    - wandb==0.12.16
